kind: pipeline
name: server

steps:
  - name: ping
    image: mongo:3.6
    commands:
      - sleep 5
      - mongo --host mongo --eval "db.version()"

  - name: test
    image: virtool/external-tools:0.1.2

    commands:
      - pip install -qr requirements.txt
      - pytest -x --db-connection-string mongodb://mongo:27017 --cov --cov-report xml

  - name: coverage
    image: python:3.6-alpine
    environment:
      CODACY_PROJECT_TOKEN:
        from_secret: CODACY_PROJECT_TOKEN
    commands:
      - apk add git
      - pip install codacy-coverage
      - python-codacy-coverage -r coverage.xml -c $DRONE_COMMIT_SHA -d $PWD
    when:
      event:
        - push

services:
  - name: mongo
    image: mongo:3.6
    command: [--smallfiles, --nojournal]
    ports:
      - 27017

---
kind: pipeline
name: client

steps:
  - name: test
    image: node:12-alpine
    commands:
      - cd client
      - npm i
      - npx jest --coverage

  - name: coverage
    image: node:12-alpine
    environment:
      CODACY_PROJECT_TOKEN:
        from_secret: CODACY_PROJECT_TOKEN
    commands:
      - cd client
      - npm i codacy-coverage
      - cat ./coverage/lcov.info | npx codacy-coverage -c $DRONE_COMMIT_SHA
    when:
      event:
        - push

---
kind: pipeline
name: build

steps:
  - name: client
    image: node:12-stretch
    commands:
      - cd client
      - npm i
      - npx webpack --config webpack.production.config.babel.js
